<?php
//Form
module_load_include('inc', 'create_one_time_link', 'create_one_time_link.form');
//Create Link
module_load_include('inc', 'create_one_time_link', 'create_one_time_link.create_link');
//Mail Handler
module_load_include('inc', 'create_one_time_link', 'create_one_time_link.mail');



function create_one_time_link_menu() {

$items['one_time_link/create'] = array(
	'page callback' => 'create_one_time_link_page',
	//'page arguments' => array('form_create_link'),
	'access arguments' => TRUE,
	'title' => t('Create One Time Link'),
    'file' => 'create_one_time_link.page.inc'
	
	
);


    $items['one_time_link/send_email/%'] = array(
        'page callback' => 'create_one_time_link_email',
        'page arguments' => array(2),
        'access arguments' => TRUE,
        'title' => t('Send Email'),
        'file' => 'create_one_time_link.mail.inc'


    );


return $items;

}










